# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'open-now-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for open-now-ios
  pod 'SwiftProtobuf', '~> 1.0'
  target 'open-now-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'open-now-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
