// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package kevin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoreClient interface {
}

type coreClient struct {
	cc *grpc.ClientConn
}

func NewCoreClient(cc *grpc.ClientConn) CoreClient {
	return &coreClient{cc}
}

// CoreServer is the server API for Core service.
type CoreServer interface {
}

func RegisterCoreServer(s *grpc.Server, srv CoreServer) {
	s.RegisterService(&_Core_serviceDesc, srv)
}

var _Core_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kevin.Core",
	HandlerType: (*CoreServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_1ea4c4411d23821c) }

var fileDescriptor_service_1ea4c4411d23821c = []byte{
	// 59 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x4e, 0x2d, 0xcb, 0xcc,
	0x33, 0x62, 0xe3, 0x62, 0x71, 0xce, 0x2f, 0x4a, 0x4d, 0x62, 0x03, 0x8b, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x3e, 0x83, 0x4d, 0x5e, 0x26, 0x00, 0x00, 0x00,
}
